COMMON:               ## Common values that apply to all modules
  SHAPE: [480, 640] ## Image shape (h, w) [uint, uint]

IO:                   ## Config for image input/output
  CAPTURE: 0          ## Camera index or video path [uint | str]
  SAVE: False         ## Whether to save images/videos [bool]
  SAVE_PATH: 'output' ## Path to save directory [str]
  SAVE_FORMAT: 'mp4'  ## Save format, either one of video formats or one of image formats [str]
  FPS: 30             ## Frames per second [uint]

VIS:                  ## Config for image visualizer
  WINNAME: 'Fingers'  ## OpenCV window name
  INSPECT_KEY: 'c'    ## Key to press to inspect intermediate image
  BREAK_KEY: 'q'      ## Key to press to quit out of program
  CONTINUE_KEY: 'd'   ## Key to press to go to next processing step
  BACK_KEY: 'a'       ## Key to press to go to previous processing step

PROCESSING:           ## Config for image processing
  COLOR_BOUNDS:       ## HSV lower and upper bounds for skin detection
    LOW:              ## HSV lower bounds [Dict[str, uint8]]
      H: 0
      S: 15
      V: 150
    HIGH:             ## HSV upper bounds [Dict[str, uint8]]
      H: 40
      S: 255
      V: 250
  BLUR_SIZE: 7        ## Blur kernel size for gaussian blurring [uint]
  CLOSE_SIZE: 3       ## Mothpology kernel size for closing operation [uint]
  CLOSE_ITERS: 3      ## How many iterations of closing to use [uint]